version: '3.8'

services:
  website-performance-tool-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: website-performance-tool-dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - HOSTNAME=0.0.0.0
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    restart: unless-stopped
    networks:
      - website-performance-tool-dev-network
    stdin_open: true
    tty: true

networks:
  website-performance-tool-dev-network:
    driver: bridge