version: '3.8'

services:
  website-performance-tool:
    image: docker.io/${DOCKERHUB_USERNAME:-233bit}/${REPO_NAME:-website-performance-tool}:latest
    container_name: website-performance-tool
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - website-performance-tool-network

networks:
  website-performance-tool-network:
    driver: bridge

volumes:
  website-performance-tool-data:
    driver: local